[package]
name = "rupa"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0"
clap = { version = "4", features = ["derive"] }
colored = "2.1"
env_logger = "0"
log = "0.4"
